apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: si-worker-1-volume-claim
  labels:
      app: wso2si-worker-1
      pattern: wso2si-active-active
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi