apiVersion: v1
data:
  db-install.sql: 
    GRANT CONNECT ON DATABASE pushpin to rtuser;
    CREATE SCHEMA IF NOT EXISTS realtime;
    CREATE TABLE realtime.pushpin_subscription(
    channel character varying COLLATE pg_catalog."default" NOT NULL,
    nodes character varying[] COLLATE pg_catalog."default",
    CONSTRAINT pushpin_subscription_pkey PRIMARY KEY (channel));
  db-uninstall.sql: 
    DROP SCHEMA IF EXISTS realtime CASCADE;

  db.install: 'true'
kind: ConfigMap
metadata:
  name: psql-script-config
  # namespace: wso2