# Start with a base image containing Java runtime
FROM openjdk:8-jdk-alpine

 

# Add Maintainer Info
LABEL maintainer="nnallapu35@gmail.com"

 

# Add a volume pointing to /tmp
VOLUME /tmp


RUN mkdir -p  /siddhi-files/

copy ABCD.siddhi  /siddhi-files
 

# Make port 8000 available to the world outside this container
EXPOSE 8000

 

# The application's jar file
ARG JAR_FILE=target/NanoHTTPD-0.0.1-SNAPSHOT.jar

 

# Add the application's jar to the container
ADD ${JAR_FILE} java-backend.jar

 

# Run the jar file 
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar", "/java-backend.jar"]