
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushpin-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushpin-backend
  template:
    metadata:
      labels:
        app: pushpin-backend
    spec:
      containers:
      - name: pushpin-backend
        image: nnallapu/pushpin-backend-service-v2:1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
      # - name: siddhi-runner
      #   image: siddhiio/siddhi-runner-alpine:latest
      #   imagePullPolicy: Always
      #   ports:
      #   - containerPort: 8006
      #   - containerPort: 9090
      #   - containerPort: 9443
---
apiVersion: v1
kind: Service
metadata:
  name: pushpin-backend-svc
spec:
  selector:
    app: pushpin-backend
  clusterIP: None
  ports:
  - name: http
    port: 8000
    targetPort: 8000        
---
      

       
