apiVersion: v1
kind: ConfigMap
metadata:
  name: pushpin-config
data:
  routes: |
    *,proto=ws pushpin-backend-svc:8000,over_http
    *,proto=http localhost:8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushpin-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushpin
  template:
    metadata:
      labels:
        app: pushpin
    spec:
      containers:
      - name: pushpin
        image: fanout/pushpin
        ports:
        - containerPort: 7999
        - containerPort: 5560
        - containerPort: 5561
        - containerPort: 5562
        volumeMounts:
        - name: pushpin-config
          mountPath: /etc/pushpin/routes
          subPath: routes
      # - name: siddhi-runner
      #   image: siddhiio/siddhi-runner-alpine:latest
      #   imagePullPolicy: Always
      #   ports:
      #   - containerPort: 8006
      #   - containerPort: 9090
      #   - containerPort: 9443
      volumes:
      - name: pushpin-config
        configMap:
          name: pushpin-config  

       
---
apiVersion: v1
kind: Service
metadata:
  name: pushpin-svc
spec:
  selector:
    app: pushpin
  clusterIP: None
  ports:
  - name: http
    port: 7999
    targetPort: 7999
  - name: http1
    port: 5560
    targetPort: 5560  
  - name: http2
    port: 5561
    targetPort: 5561
  - name: http3
    port: 5562
    targetPort: 5562          
---