# Copyright (c) 2018, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushpin-java-backend
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: pushpin-java-backend
  template:
    metadata:
      labels:
        app: pushpin-java-backend
        node: docker-desktop
    spec:
      initContainers:
      - name: init
        image: nnallapu/db-init-script:1.0
        command: ['sh', '-c', cp /data/*  /dbsql/]
        volumeMounts:
          - name: dbsql
            mountPath: "/dbsql"
      containers:
      - name: pushpin-java-backend
        image: nnallapu/rt-backend-java-service:1.0
        name: pushpin-java-backend
        imagePullPolicy: Always
        ports:
        -
          containerPort: 8000
          protocol: "TCP" 
        volumeMounts:
            - name: dbsql
              mountPath: "/docker-entrypoint-initdb.d/"
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 70
          periodSeconds: 20  
      #nodeSelector:#
        #platts-node-group:#
      volumes:
          - name: dbsql
            emptyDir: {}